package pogobattles.battle.strategies;

public enum AttackStrategyType {
  NONE,
  QUICK_ATTACK_ONLY,
  DEFENSE,
  CINEMATIC_ATTACK_WHEN_POSSIBLE,
  DEFENSE_RANDOM,
  DEFENSE_LUCKY,
  DODGE_SPECIALS,
  DODGE_ALL,
  DODGE_SPECIALS2,
  DODGE_ALL2,
  DODGE_SPECIALS3,
  DODGE_ALL3,
  DODGE_ALL_CAUTIOUS_HUMAN,
  DODGE_ALL_REASONABLE_HUMAN,
  DODGE_ALL_RISKY_HUMAN,
  DODGE_ALL_RECKLESS_HUMAN,
  DODGE_SPECIALS_HUMAN
}
